### ISSUE TITLE
Writing to display gives weird characters

### ISSUE THREAD

**Issue by CaptainMack** [Qasemt/ilcd#1]
Hi Qasemt!

Thanks for sharing this library. I can use the Display/Backlight functions perfectly, however,
I cannot write anything to the display (I'm using the LCD 1602) with a Raspberry Pi 2.

It comes out as either weird characters (seems russian) or writes something like "DW 7G".

Any idea what the issue could be?

**Comment by Qasemt** [comment]
hi :)
May be you are running your LCD at 5 volts and your I2C system is at 3.3 volts or inverse to this point 
(i2c 5v -lcd 3.3)

**Comment by CaptainMack** [comment]
Hi Qasemt,

Thank you for your reply. I'm using a I2C module that's built onto the 16x2 LCD. I've tried switching its' VCC wiring to 3.3V, but to no avail. It simply becomes darker and I still cannot write anything to the display. Can I programmatically, switch the I2C on the raspberry pi 2 to run on 5V? Or am I missing the point here?

Thanks,
Chris

**Comment by Qasemt** [comment]
hi
 i don't know  with programmatically way
but i m used this elements

**links :** 
- http://www.ebay.com/itm/like/171225323106 <br>
- http://www.ebay.com/itm/like/261590170368 <br>

![alt text](http://shop.aftabrayaneh.com/image/cache/data/arduino/Displays/LCD1602-I2C-Driver/LCD1602-I2C-Driver%20%281%29-500x500.jpg)
![alt text](http://shop.aftabrayaneh.com/image/cache/data/arduino/Displays/1602A-5v/1602A_5v_2-500x500.jpg)
