### ISSUE TITLE
install error. 

### ISSUE THREAD

**Issue by broo0ose** [Qasemt/ilcd#2]
Hi, 

I'm having trouble installing this into node-red. 
running `npm install ilcd` in the .node-red directory.  
Screen output is here, http://pastebin.com/HdCftT7A
the log file is not created. 

thanks for reading

Edit: this is using Raspbian Lite, fresh install with node.js. v4.6.1

**Comment by Qasemt** [comment]
sorry,I don't have experience in node-red field

**Comment by broo0ose** [comment]
I've been doing some research,  

I think the issue is with the i2c library your code uses and node.js v4
this link shows the same issues. 
https://github.com/kelly/node-i2c/issues/69  

There's an update that is meant to fix it here, https://github.com/kelly/node-i2c/pull/77
but I don't know if your code uses that fix. 

Edit: looking at your packages.json you have referenced i2c v0.2.0 and that fix is in 0.2.3

**Comment by broo0ose** [comment]
I cloned ilcd and changed the package.json so that i2c was version 0.2.3 and it works!

**Comment by broo0ose** [comment]
could you update package.json so that i2c is version 0.2.3 please. Then this issue could be closed.

**Comment by Qasemt** [comment]
fixed ;) tanx
